# Generated by Django 4.2 on 2026-07-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_porterprofile_phone_number_alter_farmerprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='membership_number',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='porterprofile',
            name='route_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
